#pragma once
#if SK_PLOT
#define SOLAR_OS_PACKAGE_APP_PLOT 1
#endif
#if SK_PLAYGROUND
#define SOLAR_OS_PACKAGE_APP_PLAYGROUND 1
#endif
#if SK_TEXT_APPS
#define SOLAR_OS_PACKAGE_APP_LESS 1
#define SOLAR_OS_PACKAGE_APP_NOTES 1
#define SOLAR_OS_PACKAGE_APP_SHEET 1
#endif
/* Incremental USB shell profile; enable only integrated applications. */
#define SOLAR_OS_PACKAGE_CORE_FS_COMMANDS 1
#define SOLAR_OS_PACKAGE_APP_CALC 1
#define SOLAR_OS_PACKAGE_APP_EDIT 1
#define SOLAR_OS_PACKAGE_APP_PYTHON 1

#if SK_AUDIO_PLAYER
#define SOLAR_OS_PACKAGE_APP_APLAY 1
#define SOLAR_OS_PACKAGE_APP_ARECORD 1
#define SOLAR_OS_PACKAGE_SERVICE_AUDIO_CODECS 1
#endif

#if SK_ETHERNET
#define SOLAR_OS_PACKAGE_SERVICE_NETWORK 1
#define SOLAR_OS_PACKAGE_SERVICE_NET 1
#endif

#if SK_SSH
#define SOLAR_OS_PACKAGE_APP_SSH 1
#endif

#if SK_FILES
#define SOLAR_OS_PACKAGE_APP_FILES 1
#endif

#if SK_SYNTH
#define SOLAR_OS_PACKAGE_APP_SYNTH 1
#endif
