#pragma once
#if SK_WEBRADIO
#define SOLAR_OS_PACKAGE_APP_WEBRADIO 1
#endif
#if SK_UPSTREAM_SHELL
#define SOLAR_OS_PACKAGE_APP_LTOP 1
#endif
#if SK_HW_RESOURCES
#define SOLAR_OS_PACKAGE_APP_COM 1
#define SOLAR_OS_PACKAGE_APP_IO 1
#endif
#if SK_SCOPE
#define SOLAR_OS_PACKAGE_APP_SCOPE 1
#endif
#if SK_POWER
#define SOLAR_OS_PACKAGE_APP_PDPOWER 1
#endif
#if SK_CLOCK
#define SOLAR_OS_PACKAGE_APP_CLOCK 1
#endif
#if SK_OBD
#define SOLAR_OS_PACKAGE_APP_OBD 1
#endif
#if SK_MQTT_EXPLORER
#define SOLAR_OS_PACKAGE_APP_MQTT_EXPLORER 1
#endif
#if SK_GRAPHICS
#define SOLAR_OS_PACKAGE_APP_VIEW 1
#define SOLAR_OS_PACKAGE_APP_INVADERS 1
#endif
#if SK_PLOT
#define SOLAR_OS_PACKAGE_APP_PLOT 1
#endif
#if SK_PLAYGROUND
#define SOLAR_OS_PACKAGE_APP_CURL 1
#define SOLAR_OS_PACKAGE_APP_PLAYGROUND 1
#endif
#if SK_TEXT_APPS
#define SOLAR_OS_PACKAGE_APP_DOCS 1
#define SOLAR_OS_PACKAGE_APP_LESS 1
#define SOLAR_OS_PACKAGE_APP_NOTES 1
#define SOLAR_OS_PACKAGE_APP_SHEET 1
#endif
/* Incremental USB shell profile; enable only integrated applications. */
#define SOLAR_OS_PACKAGE_CORE_FS_COMMANDS 1
#define SOLAR_OS_PACKAGE_APP_CALC 1
#define SOLAR_OS_PACKAGE_APP_EDIT 1
#define SOLAR_OS_PACKAGE_APP_PYTHON 1

#if SK_AUDIO_PLAYER
#define SOLAR_OS_PACKAGE_APP_APLAY 1
#define SOLAR_OS_PACKAGE_APP_ARECORD 1
#define SOLAR_OS_PACKAGE_SERVICE_AUDIO_CODECS 1
#endif

#if SK_ETHERNET
#define SOLAR_OS_PACKAGE_SERVICE_NETWORK 1
#define SOLAR_OS_PACKAGE_SERVICE_NET 1
#endif

#if SK_SSH
#define SOLAR_OS_PACKAGE_APP_SSH 1
#define SOLAR_OS_PACKAGE_SERVICE_SSH 1
#endif

#if SK_FILES
#define SOLAR_OS_PACKAGE_APP_FILES 1
#endif

#if SK_SYNTH
#define SOLAR_OS_PACKAGE_APP_SYNTH 1
#endif
